baseurl = "https://akherlan.github.io/blog"
publishdir = "docs"
languageCode = "en-us"
title = "Engineer of words"
author = "Andi"
theme = "hugo-lithium"
enableEmoji = true
googleAnalytics = ""
disqusShortname = "andikh"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"

[params]
    description = "Catatan bukan blog"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml", "ruby", "sql", "py", "bash"]
    highlightjsTheme = "dark"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "kucing"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true