---
title: Cerita Saya Ketika 2016
author: ''
date: []
slug: about
categories: []
tags: []
---

Saya memperkenalkan diri kepada khalayak sebagai seorang [mahasiswa teknik](https://medium.com/efekrumahbaca/kalkulasi-hidup-b478a8236ebc). Saya punya cita-cita membangun sebuah perusahaan rintisan (*start-up*). Ingin bekerja di daerah tempat saya dibesarkan sebagai apapun, atau memiliki pekerjaan yang bisa dibawa kemanapun saat saya ingin pindah atau pergi. Beberapa orang mungkin ingin seperti itu, tetapi sebagian tidak. Kemudian dapat menikah sesegera mungkin agar kelak semangat hidup selalu dapat diperbaharui. Sesederhana itulah di mata dunia.

Mimpi terpendam saya adalah mengunjungi tempat-tempat yang belum pernah saya kunjungi, mengetahui berbagai bahasa dan budaya. Membandingkan pola pikir berbagai kaum merupakan hal yang dapat membuat saya selalu [belajar tentang kehidupan](https://t.me/cpauthor). Senantiasa melakukan “diskusi” dengan segala bentuk ciptaan Tuhan, seraya memperbaharui status saya di “jejaring sosial” milik-Nya, adalah hal yang menurut saya penting untuk selalu diperhatikan. Dengan demikian saya akan merasa sangat kecil dan tak berdaya dalam ilusi yang dibuat-Nya.

Mengenai kegiatan belajar, saya tidak tahu apakah ijazah benar-benar sepenting yang dipikirkan orang-orang. Bagi saya, belajar dari hal-hal yang saya sukai lebih berguna untuk saya pribadi daripada sekadar gelar dan jabatan. Namun, saya melakukannya, sekolah hingga tinggi. Karena proses belajar tidak akan pernah berhenti sepanjang hidup dan dapat diperoleh dari jalan manapun. Saya mencoba segala jalan.

Dengan bekal keingintahuan tentang masa depan, berkeinginan melupakan keburukan di masa lalu, serta berusaha menjalankan sebaik-baiknya masa kini, maka halaman demi halaman dalam blog profil ini dibuat. Semoga pembaca dapat menikmati.

---

*Blog ini tersimpan di* [*Github*](https://github.com/akherlan/blog)*. Dibuat menggunakan paket* [*`blogdown`*](https://github.com/rstudio/blogdown) *di RStudio, dengan tema* [*Hugo Lithium*](https://github.com/jrutheiser/hugo-lithium-theme) *yang telah dimodifikasi oleh* [*Yihui Xie*](https://github.com/yihui/hugo-lithium)*, lalu* [*saya*](https://t.me/akherlan) *sesuaikan.*

*Seluruh konten berada di bawah Lisensi* [***CC BY-SA 4.0***](https://creativecommons.org/licenses/by-sa/4.0/deed.id)*.*
