---
title: "Tema Hugo Lithium Tidak Responsif"
author: "andikh"
date: '2019-03-26'
slug: tema-hugo-lithium-tidak-responsif
tags: website
categories: belajar
---

Ini merupakan tulisan dokumentasi saya untuk permasalahan tema Lithium yang tidak responsif (saat hari ini saya gunakan). Ukuran gambar tidak menyesuaikan ukuran layar. Sangat fatal ketika dibuka dari ponsel, mengingat sebagian besar akses internet hari ini adalah melalui ponsel. Alamak!

Awalnya saya tanya di grup [GNU/R Indonesia](https://t.me/GNURIndonesia), padahal ini tidak ada kaitannya sama sekali dengan pemrograman R. Tetapi karena saya ngeblog dari R menggunakan paket `blogdown`, jadi saya coba tanyakan saja. Cocoklogi. Hihihi... Ada saran, ganti tema yang responsif saja, atau tambahkan skrip bootstrap di dalamnya, alamak! Nggak ngerti!

Saya tidak menyerah, tetap *searching*... Ketemu!

Ada orang yang baik hati menambahkan fitur responsif pada tema Lithium yang saya pakai ini. Entah apa motifnya, karena pada akhirnya templat itu pun ternyata tidak ia gunakan. Tapi, ya sudah. Saya bersyukur.

Namun ada satu kendala lagi. Saya harus mencari bagian mana yang diubah. Saya tidak langsung mengganti tema Lithium yang saya gunakan (dari [yihui](https://github.com/yihui/hugo-lithium)) dengan tema Lithium modifikasi yang baru (dari [jrutheiser](https://github.com/jrutheiser/hugo-lithium-theme)).

Untungnya ketemu, ada di dalam `main.css`, seperti berikut:

```{css}
img {
  max-width: 100%;
  height: auto;
}
```

*Voila!* Ukuran gambar di blog ini sudah menyesuaikan ukuran layar. Sudah. Ternyata begitu saja. 

Sekian. Terima kasih.